version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    container_name: elasticsearch
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - stack

  logstash:
     image: docker.elastic.co/logstash/logstash:5.4.0
     container_name: logstash
     environment:
      - xpack.monitoring.enabled=false
     depends_on:
      - elasticsearch
     networks:
      - stack

  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.0
    container_name: kibana
    ports:
      - "127.0.0.1:5601:5601"
    networks:
      - stack
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local

networks:
  stack:

volumes:
  esdata:
    driver: local

networks:
  stack:
